---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "docs/figs/"
)
```


# hhmcseirv

[`hhmcseirv`](https://github.com/SC-COSMO/hhmcseirv) is a code repository that implements a multi-compartment susceptible-exposed-infected- recovered-susceptible-vaccinated (MC-SEIRSV) model with demography accounting for community and household transmission.

[`hhmcseirv`](https://github.com/SC-COSMO/hhmcseirv) is part of the following manuscript:

- Alarid-Escudero F, Andrews J, Goldhaber-Fiebert JD. [Effects of Mitigation and Control Policies in Realistic Epidemic Models Accounting for Household Transmission Dynamics](https://www.medrxiv.org/content/10.1101/2023.01.26.23285075v2). Under review. 2023. 

# Preprint
- Alarid-Escudero F, Andrews J, Goldhaber-Fiebert JD. [Effects of Mitigation and Control Policies in Realistic Epidemic Models Accounting for Household Transmission Dynamics](https://www.medrxiv.org/content/10.1101/2023.01.26.23285075v2). medRxiv 2023;v3. 10.1101/2023.01.26.23285075

## Acknowledgements

Our work was partly supported by a grant from the Society for Medical Decision Making (SMDM), funded by the Gordon and Betty Moore Foundation, a grant from Open Society Foundations (OSF), a gift from the Wadhwani Institute for Artificial Intelligence Foundation, and Advanced Micro Devices (Santa Clara, CA, USA) provided a donation of servers. The funders had no role in study design, data collection, data analysis, data interpretation, writing of the article, or the decision to submit for publication.
